### ISSUE TITLE
New version breaks webpack integration

### ISSUE THREAD

**Issue by rezaffm** [selectize/selectize.js#1421]
Webpack setup (quite easy)

window.$ = window.jQuery = require('jquery');
require('selectize');

used to work perfectly (0.12.4) - now following message appears in console:

"TypeError: $(...).selectize is not a function[Weitere Informationen]"

I tried several things in webpack, such as use imports-loader - or adding dependencies to the window object. No chance, always received that error.

Best, S

**Comment by soulchild** [comment]
JFYI, we've experienced the same issue with Browserify since upgrading to 0.12.5 (from 0.12.4).

**Comment by hayzem** [comment]
I am experiencing the same problem. Is there any workaround without downgrading it?

**Comment by rezaffm** [comment]
Well, indeed there is a workaround, but I am quite confused. So here comes the solution:

`(function(root, factory) {
	console.log(root);
	if (typeof define === 'function' && define.amd) {
		define(['jquery','sifter','microplugin'], factory);
	} else if (typeof exports === 'object') {
		module.exports = factory(require('jquery'), require('sifter'), require('microplugin'));
	} else {
		root.Selectize = factory(root.jQuery, root.Sifter, root.MicroPlugin);
}`

Normally, it is fine when you prevent the plugin from loading the first part (define === false). The second part should actually work then. Well, this part also does not work (for some reason I cannot explain. So basically I did the following:

First in our entry.js (or main, app.js...) set the window variables:

import $ from 'jquery';
window.$ = window.jQuery = $;
window.Sifter = require('sifter');
window.MicroPlugin = require('microplugin')

then you need to install import-loader, here you set define and exports to false. Also, you have to include "this=>window", in order to pass through the window on which you set the other instances. I ve noticed that this was not set properly, so I tried to pass the window instance through. 

require("imports-loader?this=>window,define=>false,exports=>false!selectize");

and here you are... it works...weird

**Comment by jaimeperez** [comment]
This needs attention, as the last release breaks selectize completely for everyone using webpack and requiring a more modern version of jQuery than the 1.x branch.

I can confirm that #1414 resolves this problem. It can be tested specifying the dependency like this:

```json
"dependencies": {
    "jquery": "~3.3.1",
    "selectize": "graingert/selectize.js#patch-1",
},
```

**Comment by rezaffm** [comment]
Interesting, so your dont get the same error with jQuery 1.x?
Well, webpack and other bundlers shd be supported.

**Comment by jaimeperez** [comment]
I haven't tried myself, but I believe you won't. The problem is that when you require a version of jQuery (3.x) that's not compatible with the new requirement in the `package.json` here (`^1.7.0`) both versions get then installed. Now, upon initialization, selectize registers itself inside the 1.x version of jQuery, while your code uses the 3.x version, hence the error.

**Comment by jsgoupil** [comment]
The jQuery version loaded with webpack and selectize 0.12.5 is this one:
`__webpack_require__(/*! jquery */ "./node_modules/selectize/node_modules/jquery/dist/jquery.js")`

But then when I load jQuery across my application, it doesn't load it from node_modules/selectize. So the fn.selectize does not exist.

0.12.4 used to be the following:
`__webpack_require__(/*! jquery */ "./node_modules/jquery/dist/jquery.js")`

**Comment by LeRoyJulian** [comment]
Just lost an hour trying to understand what was happening... Please fix this.

**Comment by joallard** [comment]
Can I get another confirmation #1414 fixes this?

**Comment by M-BenAli** [comment]
> Can I get another confirmation #1414 fixes this?

This is an old issue but still a problem as of version `0.12.6`, still receiving the following error: `Uncaught TypeError: $(...).selectize is not a function`. Downgrading to `0.12.4` as suggested by some earlier comments didn't do the trick for me. A temporary solution I can think of is to manually import the library into my project(which I really want to avoid).

**Comment by willjohnson** [comment]
@M-BenAli Were you able to find a fix for this?

**Comment by M-BenAli** [comment]
> @M-BenAli Were you able to find a fix for this?

No I wasn't able to find a fix, a temporary solution is to still use sprockets for the JS libraries that do not work in webpacker which I am doing. The idea is that they have to be migrated over to webpacker eventually or the libraries just have to be replaced by something that is compatible if there is no fix.

**Comment by Uysim** [comment]
I face the same problem. Did we manage to fixed it?

**Comment by Pictor13** [comment]
> The jQuery version loaded with webpack and selectize 0.12.5 is this one:
> `__webpack_require__(/*! jquery */ "./node_modules/selectize/node_modules/jquery/dist/jquery.js")`
> 
> But then when I load jQuery across my application, it doesn't load it from node_modules/selectize. So the fn.selectize does not exist.
> 
> 0.12.4 used to be the following:
> `__webpack_require__(/*! jquery */ "./node_modules/jquery/dist/jquery.js")`

Mmmh, the jQuery dependency has been moved from `dependencies` to `peerDependencies`. I think that's all that really changed. Anybody know if that would affect the flattening of dependencies or how Webpack is influenced by that change?

Since then one need to explicitly install the desired jQuery version in their project (except when installing for actual Selectize development).

I am not sure why, with 0.12.5, Webpack reports that nested node_modules path.
Isn't NPM (>= 3) supposed to flatten the dependencies, so that they are all under the same/single `node_modules/`?

I can guess two options, for now:

1. You have NPM <3, and the hierarchy structure is not being flattened, hence making webpack look in a nested folder (I don't know what webpack does here; it's just a guess). Try a newer NPM version.

2. Your project that uses Selectize does **not** install any version of *jQuery* hence it crashes; and you should manually `npm install --save jquery` to be explicit (this is the main change that can break projects, since the dep has been moved to `peerDependencies`).
Still, I wouldn't understand why looking for it into a nested folder; maybe, as at the point 1, is some kind of fallback when webpack cannot find into the top-most `node_modules/` folder? (<--- speculating like pro 😎😝)
